### ISSUE TITLE
Error loading Python DLL on Windows 7

### ISSUE THREAD

**Issue by lontivero** [bitcoin-core/HWI#150]
A Wasabi wallet user who is helping to test the HW integration got this error:

![Screenshot from 2019-04-17 02-24-15](https://user-images.githubusercontent.com/127973/56263177-50f51a00-60b8-11e9-983b-b1dd483d9f23.png)

It looks like a library dependency problem. Is the binary cli tool expected to work on Win7?

**Comment by achow101** [comment]
It should work on Win7 but I didn't test it (I don't have a Win7 machine).

Is it a 32-bit install? HWI currently doesn't support 32-bit OSes (I can make 32-bit builds if necessary).

**Comment by Kortik7** [comment]
Hi, it was me that @lontivero posted earlier. I tired installing this visual studio but still same error. I have win7 Ultimate 64bit

![photo_2019-04-16_23-21-33](https://user-images.githubusercontent.com/49734532/56323275-2d65ba00-6120-11e9-82de-e657f778b569.jpg)

**Comment by nopara73** [comment]
Wasabi doesn't support 32 bit machines, so it will never be necessary for us.

**Comment by Kortik7** [comment]
> Wasabi doesn't support 32 bit machines, so it will never be necessary for us.

I have win 7 Ultimate 64bit version.

**Comment by achow101** [comment]
I got a Windows 7 VM running and was able to reproduce this error. I'm currently investigating the cause and possible solutions. I think it may be related to the caveat mentioned here: https://pyinstaller.readthedocs.io/en/stable/usage.html#windows.

I'm trying to see if packaging the C++ Runtime DLLs with the binary will make it work.

**Comment by lontivero** [comment]
I also think it is because C++ runtime and that was the first thing @Kortik7 tried. He also tried installing the [Windows x86-64 embeddable zip file](https://www.python.org/ftp/python/3.6.0/python-3.6.0-embed-amd64.zip). Btw, he also tried installing the [ Windows Software Development Kit (SDK) for Windows 10](https://dev.windows.com/en-us/downloads/windows-10-sdk) as you can see in the screenshot. Finally I tried building the Windows binary with an older version of python but it only works for python >= 3.6.

But I didn't have a Win7 neither so, I still believe that one of this three things should have to work.

**Comment by achow101** [comment]
I did a build using Windows 7 and the resulting binary did work. Inspecting it showed that it included a bunch of DLLs which can be found in the Windows SDK for Windows 10. I'll see if including those in the binary with the wine build method will work.

**Comment by Kortik7** [comment]
> I did a build using Windows 7 and the resulting binary did work. Inspecting it showed that it included a bunch of DLLs which can be found in the Windows SDK for Windows 10. I'll see if including those in the binary with the wine build method will work.

I just installed https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk mine was outdated but I still get the same missing python36.dll file.

**Comment by achow101** [comment]
@Kortik7 Can you try the hwi.exe file at https://github.com/achow101/hardware-wallet-interface/releases/tag/win7-fix

**Comment by nopara73** [comment]
@achow101 I got to my old Windows 7 and to this issue. Hopefully I will be able to work on this issue tomorrow.

I can reproduce the issue. I can confirm that your fix does not solve it.

![image](https://user-images.githubusercontent.com/9156103/56445551-b4b85680-62f5-11e9-93e6-5ba72892228c.png)

**Comment by achow101** [comment]
@Kortik7 @nopara73 I believe I've fixed the issue and uploaded a new binary at https://github.com/achow101/hardware-wallet-interface/releases/tag/win7-fix. Can you try try that?

**Comment by Kortik7** [comment]
> @Kortik7 @nopara73 I believe I've fixed the issue and uploaded a new binary at https://github.com/achow101/hardware-wallet-interface/releases/tag/win7-fix. Can you try try that?

I tried your method. and it fixed enumeration but I think there is a wasbi bug ledger Nano S still does not recognize.  
![photo_2019-04-19_21-30-07](https://user-images.githubusercontent.com/49734532/56454364-4f1f9680-6304-11e9-977a-9183492141c3.jpg)

**Comment by nopara73** [comment]
It's fixed. @Kortik7 no worry. We just check the hash of the software when start Wasabi and if not the same then reinstall hwi. So Wasabi still uses the same old one.

**Comment by Kortik7** [comment]
@nopara73 I was able to connect but my ledger shows zero balance. But I have balance on it.

![Untitled](https://user-images.githubusercontent.com/49734532/56454903-c5c09200-630c-11e9-901c-f571f10e0105.png)

**Comment by nopara73** [comment]
Now you're Ledger does: )
