### ISSUE TITLE
Trezor emulator is seen as both trezor and keepkey

### ISSUE THREAD

**Issue by Sjors** [bitcoin-core/HWI#517]
Using the 2.0.2 release with the latest Trezor emulator build:
```
hwi  --device-type trezor enumerate
```

```
[{"type": "trezor", "path": "udp:127.0.0.1:21324", "model": "trezor_t_simulator", "needs_pin_sent": false, "needs_passphrase_sent": false, "fingerprint": "a904f46a"}, {"type": "keepkey", "model": "keepkey", "path": "udp:127.0.0.1:21324", "error": "Could not open client or get fingerprint information: Unsupported device", "code": -13}]
```

**Comment by prusnak** [comment]
I asked Keepkey to change their emulator port: https://github.com/keepkey/keepkey-firmware/issues/276

**Comment by prusnak** [comment]
https://github.com/keepkey/keepkey-firmware/issues/276 has been closed - we can change the Keepkey's port from 21324 to 11044

**Comment by prusnak** [comment]
Fix in https://github.com/bitcoin-core/HWI/pull/519

**Comment by Talkless** [comment]
I see fix is merged, so I've checkouted master, but still got this issue:

```
$ git status | fgrep branch
On branch master
$ ./hwi.py enumerate
[{"type": "trezor", "path": "udp:127.0.0.1:21324", "model": "trezor_t_simulator", "needs_pin_sent": false, "needs_passphrase_sent": false, "fingerprint": "c664c2b7"}, {"type": "keepkey", "model": "keepkey", "path": "udp:127.0.0.1:21324", "error": "Could not open client or get fingerprint information: Unsupported device", "code": -13}]
```
Still "keepkey" ?

**Comment by prusnak** [comment]
@Talkless Have you updated (and rebuilt) the keepkey emulator? Because it seems you are still running the old keepkey code.

**Comment by josibake** [comment]
> Have you updated (and rebuilt) the keepkey emulator?

the original issue was about using the trezor emulator, and it seems as tho the issue still exists. i pulled the latest branch of HWI, updated and rebuilt the trezor emulator and i am still getting the same error as @Sjors 

looks like you might have fixed an issue relating to using the keepkey emulator, @prusnak , but i would suggest this issue be re-opened as it relates to the trezor emulator.

**Comment by prusnak** [comment]
Ah, correct. Keepkey enumeration did not work as expected - fix in https://github.com/bitcoin-core/HWI/pull/521
